# Lab 1: Working with data

## Data processing with Pandas

In [7]:
# Load data
import pandas as pd


# Load the dataset in Excel format into a pandas DataFrame
grade_df = pd.read_excel('../data/final_grades.xlsx')

In [11]:
# View the first 10 rows of the DataFrame
grade_df.head(10)
# Make descriptive statistics of the DataFrame
grade_df.describe()

             Grade
count  1230.000000
mean      6.238154
std       1.605444
min       2.290000
25%       5.040000
50%       6.230000
75%       7.400000
max      10.000000

In [13]:
# Check if there are any missing values in the DataFrame
missing_values = grade_df.isnull().sum()
print("Missing values in each column:\n", missing_values)

Missing values in each column:
 Major    0
Grade    0
dtype: int64

In [14]:
# Get the value of the 'Major' 
major_names = grade_df['Major'].unique()
print(major_names)

<StringArray>
[ 'cdt', 'cnot', 'khhh', 'ckdl',  'ctm', 'cnhh', 'cnmt', 'ktck',  'vsh',
  'tdh', 'kttt', 'cnxd',  'ddt', 'cntt',  'kte', 'ckts', 'cnnl', 'khmt',
 'cbts', 'ttql']
Length: 20, dtype: str

In [16]:
# Filter the DF to include only students with major 'khmt', 'cntt' or 'ttql'

it_majors = ['khmt', 'cntt', 'ttql']
it_students_df = grade_df[grade_df['Major'].isin(it_majors)]
print(f'#IT students/#Total: {len(it_students_df)}/{len(grade_df)}')

#IT students/#Total: 338/1230

In [17]:
# Add a new column 'Result' to note "Pass" if grade >= 5, otherwise "Fail"
grade_df['Result'] = grade_df['Grade'].apply(lambda x: 'Pass' if x >= 5 else 'Fail')
# Display the first 10 rows of the updated DataFrame
grade_df.head(10)

  Major  Grade Result
0   cdt   8.21   Pass
1   cdt   9.25   Pass
2   cdt   8.50   Pass
3   cdt   3.90   Fail
4   cdt   7.50   Pass
5   cdt   7.25   Pass
6   cdt   7.06   Pass
7   cdt   7.83   Pass
8   cdt   6.40   Pass
9   cdt   6.23   Pass